# Generated by Django 3.2.7 on 2021-10-17 02:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_librotek_app', '0002_auto_20211016_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 21, 28, 51, 911744)),
        ),
        migrations.AlterField(
            model_name='book',
            name='modificationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 21, 28, 51, 911744)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 21, 28, 51, 916763)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modificationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 21, 28, 51, 916763)),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastLogin',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 21, 28, 51, 911744), verbose_name='lastLogin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='signUp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 21, 28, 51, 911744), verbose_name='signUp'),
        ),
    ]
