# Generated by Django 3.2.8 on 2021-10-26 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_librotek_app', '0004_auto_20211025_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.BigIntegerField(default=0, max_length=2000, verbose_name='pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 19, 17, 3, 755075)),
        ),
        migrations.AlterField(
            model_name='book',
            name='modificationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 19, 17, 3, 755075)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 19, 17, 3, 759081)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modificationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 19, 17, 3, 759081)),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastLogin',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 19, 17, 3, 757085), verbose_name='lastLogin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='signUp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 19, 17, 3, 757085), verbose_name='signUp'),
        ),
    ]
