# Generated by Django 3.2.8 on 2021-10-26 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_librotek_app', '0005_auto_20211025_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='editorial',
        ),
        migrations.RemoveField(
            model_name='book',
            name='volume',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Anonymous', max_length=128, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='book',
            name='publicationDate',
            field=models.CharField(max_length=4, null=True, verbose_name='publicationDate'),
        ),
        migrations.AlterField(
            model_name='book',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 19, 22, 24, 710166)),
        ),
        migrations.AlterField(
            model_name='book',
            name='modificationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 19, 22, 24, 710166)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 19, 22, 24, 714180)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modificationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 19, 22, 24, 714180)),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastLogin',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 19, 22, 24, 712176), verbose_name='lastLogin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='signUp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 19, 22, 24, 712176), verbose_name='signUp'),
        ),
    ]
