# Generated by Django 3.2.8 on 2021-10-26 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_librotek_app', '0006_auto_20211025_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 20, 59, 32, 481330)),
        ),
        migrations.AlterField(
            model_name='book',
            name='modificationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 20, 59, 32, 481330)),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.BigIntegerField(default=0, max_length=2000, null=True, verbose_name='pages'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 20, 59, 32, 488326)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modificationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 20, 59, 32, 488326)),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastLogin',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 20, 59, 32, 484324), verbose_name='lastLogin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='signUp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 20, 59, 32, 484324), verbose_name='signUp'),
        ),
    ]
