# Generated by Django 3.2.8 on 2021-10-26 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_librotek_app', '0008_auto_20211025_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 22, 2, 19, 883177)),
        ),
        migrations.AlterField(
            model_name='book',
            name='gender',
            field=models.CharField(max_length=128, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='book',
            name='modificationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 22, 2, 19, 883177)),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.BigIntegerField(default=0, null=True, verbose_name='pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=128, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 22, 2, 19, 889196)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modificationDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 22, 2, 19, 889196)),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastLogin',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 22, 2, 19, 886175), verbose_name='lastLogin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='signUp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 22, 2, 19, 886175), verbose_name='signUp'),
        ),
    ]
